name: "TODO-2-azdo"
description: "Customizable TODO-To-Azure DevOps work item converter."
author: "Chichuk Dmitrii"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "book-open"
  color: "red"
